import {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  EmbedBuilder,
  StringSelectMenuBuilder,
} from 'discord.js';
import { Colors } from './embeds.js';
import { bolt } from './emojis.js';

export interface DocPage {
  /** Short label for the jump menu */
  label: string;
  /** Embed title */
  title: string;
  /** Body — use {p} for the live prefix */
  body: string;
}

/**
 * Full Blaze documentation, in reading order.
 * Keep each `body` under ~3800 chars so Discord embed limits are safe.
 */
export const DOC_PAGES: DocPage[] = [
  {
    label: '1 · Getting started',
    title: 'Getting started',
    body: [
      'Welcome to **Blaze** — an all-purpose moderation & utility bot.',
      '',
      'This guide walks through **every feature** in order. Use the buttons below to go page by page, or jump with the dropdown.',
      '',
      '**Who can use `{p}docs`?**',
      '• The **Discord server owner**',
      '• A configured **bot owner** (`OWNER_ID` / owner list)',
      '',
      '**Prefix**',
      '• Default prefix is `{p}` (often `a`) — commands look like `{p}ban`, `{p}help`, `{p}setup`.',
      '• Change it anytime: `{p}prefix !` then use `!ban`, etc.',
      '• Check current prefix: `{p}prefix`',
      '',
      '**Quick mental model**',
      '1. Unlock the bot (`{p}botlock`) if it ignores everyone',
      '2. Run `{p}setup` to create mod channels / jail / mute role',
      '3. Configure logging, welcome, tickets, protection as needed',
      '4. Staff uses moderation commands day-to-day',
      '',
      '**Also useful**',
      '• `{p}help` — browse commands by category',
      '• `{p}help ban` — details for one command',
      '• Built-in shortcuts exist (e.g. `{p}q` = ban) — see the Aliases page later',
    ].join('\n'),
  },
  {
    label: '2 · First unlock & setup',
    title: 'First unlock & server setup',
    body: [
      '**New servers start locked.** Until a bot owner unlocks it, non-owners are **silently ignored** (no replies, no “unknown command”).',
      '',
      '### Bot lock (bot owners only)',
      '```',
      '{p}botlock',
      '{p}bl',
      '{p}serverlock',
      '```',
      'Toggles lock. When locked: only bot owners can run commands. When unlocked: everyone with Discord perms can use the bot.',
      '',
      '### Full moderation scaffold',
      '```',
      '{p}setup',
      '```',
      'Requires **Administrator**. Creates a **blaze mod** category with dedicated log channels (`bans`, `mutes`, `jail-logs`, `purge`, `server`, `messages`), a **#jail** channel, a **jailed** role, and a **Muted** role (send/react/speak denied in channels).',
      '',
      'Run this once per server before relying on jail or structured mod logs.',
      '',
      '### Prefix',
      '```',
      '{p}prefix',
      '{p}prefix !',
      '```',
      'View or set a 1–5 character prefix for this server.',
      '',
      '### Recommended first hour',
      '1. `{p}botlock` (unlock if needed)',
      '2. `{p}setup`',
      '3. `{p}logging enable`',
      '4. `{p}antinuke toggle on` (server owner / antinuke admins)',
      '5. `{p}welcome channel` + `{p}welcome enable` in your welcome channel',
      '6. `{p}ticket setup` in your support channel (optional)',
    ].join('\n'),
  },
  {
    label: '3 · Owners & permissions',
    title: 'Owners, permissions & fakeperms',
    body: [
      '**Bot owners** (env `OWNER_ID`, optional `OWNER_IDS`, plus any hard-coded owners) bypass Discord permission checks and botlock.',
      '',
      '**Server owner** can use `{p}docs` even if they are not a bot owner.',
      '',
      'Most commands still require normal Discord perms for staff, e.g.:',
      '• Ban / softban / hardban / unban → **Ban Members**',
      '• Kick → **Kick Members**',
      '• Mute / timeout / unmute / jail / warn → **Moderate Members**',
      '• Role / recentrole / strip → **Manage Roles**',
      '• Purge / snipe → **Manage Messages**',
      '• Filter / antiraid / invoke / fakepermissions → **Administrator** (or equivalent)',
      '• Welcome / tickets config / levels config / starboard / giveaway → **Manage Server**',
      '',
      '### Fake permissions',
      'Grant *bot-checked* permissions to a role without giving real Discord admin:',
      '```',
      '{p}fakepermissions perms',
      '{p}fakepermissions add @Mods ban_members kick_members',
      '{p}fakepermissions remove @Mods ban_members',
      '{p}fakepermissions list',
      '{p}fakepermissions clear @Mods',
      '{p}fp add @TrialMods moderate_members',
      '```',
      'Available names include: `ban_members`, `kick_members`, `moderate_members`, `manage_guild`, `manage_roles`, `manage_messages`, `administrator`, and more (`{p}fp perms`).',
      '',
      'Hierarchy still applies for role moves — you cannot assign roles above your highest role (bot owners bypass).',
    ].join('\n'),
  },
  {
    label: '4 · Ban / kick / mute',
    title: 'Moderation: ban, kick, mute, timeout',
    body: [
      'Durations use short forms: `30s`, `10m`, `1h`, `1d`, `2d3h` (timeouts max ~28 days).',
      '',
      '### Ban',
      '```',
      '{p}ban @user cutting',
      '{p}ban @user 1 raid cleanup',
      '{p}q @user toxicity',
      '```',
      'Optional number after the user is **message delete days** (0–7). Alias: `{p}q`.',
      '',
      '### Softban (ban → unban, wipe messages)',
      '```',
      '{p}softban @user spam',
      '{p}sban @user alt spam',
      '```',
      'Deletes ~7 days of messages then unbans so they can rejoin clean.',
      '',
      '### Hardban (ban + auto-ban on rejoin)',
      '```',
      '{p}hardban @user raid alt',
      '{p}hban @user',
      '```',
      'Run again on the same user to **remove** the hardban flag (`unhardban`).',
      '',
      '### Unban',
      '```',
      '{p}unban 123456789012345678 appealed',
      '```',
      'Uses a **user ID** (they are not in the server).',
      '',
      '### Kick',
      '```',
      '{p}kick @user toxicity',
      '```',
      '',
      '### Mute / timeout / unmute',
      '```',
      '{p}mute @user 1h chatting in wrong channel',
      '{p}timeout @user 30m cool down',
      '{p}to @user 10m',
      '{p}unmute @user cooled off',
      '```',
      '`mute` and `timeout` both apply a **Discord timeout** (not the setup Muted role). Alias: `{p}to`.',
    ].join('\n'),
  },
  {
    label: '5 · Jail, strip, warn, purge',
    title: 'Moderation: jail, strip, warns, purge',
    body: [
      '### Jail / unjail',
      'Needs `{p}setup` (or a configured jail role/channel).',
      '```',
      '{p}jail @user breaking rules',
      '{p}unjail @user',
      '```',
      'Jail strips roles (saved), adds the jailed role, and isolates them. Unjail restores saved roles.',
      '',
      '### Strip',
      '```',
      '{p}strip @user mass ping',
      '```',
      'Removes all removable roles from the member.',
      '',
      '### Warns',
      '```',
      '{p}warn @user language',
      '{p}warnings @user',
      '{p}clearwarnings @user appealed',
      '```',
      '',
      '### Purge',
      '```',
      '{p}purge 50',
      '{p}purge @user 100',
      '{p}c 25',
      '```',
      'Bulk-delete 1–1000 messages in the channel (optionally only from one user). Alias: `{p}c`. Does not count the command message itself.',
      '',
      '### Do Not Reply (DNR)',
      '```',
      '{p}dnr @user stop replying to me',
      '{p}undnr @user',
      '```',
      'If the target **replies to your messages**, they are auto-warned. After **3** strikes they can be jailed (DNR enforcement). Only **you** can remove a DNR you placed (`undnr`).',
    ].join('\n'),
  },
  {
    label: '6 · Roles',
    title: 'Roles: toggle, recent joiners, reaction roles',
    body: [
      'Roles can be passed as **@mention**, **role ID**, or **name** (exact, partial, or closest typo). Multi-word names: use quotes `"VIP Member"`.',
      '',
      '### Toggle role on a member',
      '```',
      '{p}role @user Member',
      '{p}role @user 123456789012345678',
      '{p}role @user memb',
      '```',
      'If they already have it, it is **removed**; otherwise it is **added**.',
      '',
      '### Role everyone who joined recently',
      '```',
      '{p}recentrole Member',
      '{p}recentrole 123456789012345678',
      '{p}recentrole "VIP Member"',
      '```',
      'Gives the role to every **human** who joined in the last **20 minutes** and does not already have it. Paced to avoid rate limits.',
      '',
      '### Role reaction (bot owners)',
      '```',
      '{p}rolereaction @mog-winner',
      '```',
      'In the current channel, finds people who reacted to **image** messages and offers a confirm flow to mass-assign the role.',
      '',
      '### List roles',
      '```',
      '{p}roles',
      '```',
      'Paginated list of server roles with IDs.',
    ].join('\n'),
  },
  {
    label: '7 · AutoMod filter',
    title: 'AutoMod / word filter',
    body: [
      'Requires **Administrator**.',
      '',
      '### Bootstrap',
      '```',
      '{p}filter setup',
      '{p}filter view',
      '```',
      '`setup` turns on sensible defaults (invites, spam, mass-mention).',
      '',
      '### Word list',
      '```',
      '{p}filter add badword',
      '{p}filter remove badword',
      '{p}filter list',
      '{p}filter clear',
      '```',
      '',
      '### Toggles & thresholds',
      '```',
      '{p}filter invites on',
      '{p}filter links off',
      '{p}filter spam on',
      '{p}filter caps on',
      '{p}filter massmention on',
      '{p}filter emojis on',
      '```',
      'Some toggles accept an optional threshold number after `on`/`off`.',
      '',
      '### Punishment',
      '```',
      '{p}filter punishment timeout',
      '{p}filter punishment kick',
      '{p}filter punishment ban',
      '{p}filter punishment jail',
      '{p}filter punishment delete',
      '{p}filter timeout 5m',
      '```',
      '`timeout` duration applies when punishment is timeout.',
    ].join('\n'),
  },
  {
    label: '8 · AntiRaid',
    title: 'AntiRaid',
    body: [
      'Requires **Administrator**. Protects against join floods and suspicious accounts.',
      '',
      '```',
      '{p}antiraid toggle on',
      '{p}antiraid toggle off',
      '{p}antiraid view',
      '```',
      '',
      '### Mass joins',
      '```',
      '{p}antiraid massjoin 10',
      '```',
      'Threshold = joins per ~60 seconds before raid logic trips.',
      '',
      '### New accounts / default avatars',
      '```',
      '{p}antiraid newaccounts 7',
      '{p}antiraid avatar on',
      '```',
      'Block accounts newer than N days; optionally block default-avatar joins.',
      '',
      '### Punishment & lockdown',
      '```',
      '{p}antiraid punishment ban',
      '{p}antiraid punishment kick',
      '{p}antiraid punishment timeout',
      '{p}antiraid punishment jail',
      '{p}antiraid lockdown on',
      '{p}antiraid lockdown off',
      '```',
      'Lockdown tightens @everyone send/connect permissions while active.',
      '',
      '### Logs',
      '```',
      '{p}antiraid setlogchannel',
      '```',
      'Run in the channel you want AntiRaid alerts in (or pass a channel if your parser supports it).',
    ].join('\n'),
  },
  {
    label: '9 · AntiNuke',
    title: 'AntiNuke',
    body: [
      'Bleed/Greed-style protection against mass destructive actions. Usable by the **server owner** or **AntiNuke admins** (not a normal Discord perm bit).',
      '',
      '```',
      '{p}antinuke toggle on',
      '{p}an toggle on',
      '{p}antinuke config',
      '{p}antinuke list',
      '```',
      'Enabling via `toggle on` turns **all modules on**.',
      '',
      '### Modules',
      'Each module: optional `on`/`off`, punishment, and threshold (actions per ~60s, typically 1–20).',
      '```',
      '{p}antinuke ban on',
      '{p}antinuke kick on',
      '{p}antinuke role on',
      '{p}antinuke channel on',
      '{p}antinuke webhook on',
      '{p}antinuke emoji on',
      '{p}antinuke botadd on',
      '{p}antinuke guild on',
      '```',
      'Punishments per module: `ban`, `kick`, `strip`, `timeout`.',
      '',
      '### Whitelist & admins',
      '```',
      '{p}antinuke whitelist @trusted',
      '{p}antinuke admin @coowner',
      '```',
      'Whitelisted users are ignored by AntiNuke triggers. Admins can configure AntiNuke.',
      '',
      'Aliases: `{p}an`, `{p}antin`.',
    ].join('\n'),
  },
  {
    label: '10 · Logging & invoke',
    title: 'Logging & custom mod messages (invoke)',
    body: [
      '### Logging',
      '```',
      '{p}logging enable',
      '{p}logging disable',
      '{p}logging channel',
      '{p}logging view',
      '```',
      '`setup` already wires dedicated log channels. `logging channel` sets a **fallback**. `view` shows status + channel map.',
      '',
      'Typical dedicated channels after setup: bans, mutes, jail, purge, server (roles/channels), messages.',
      '',
      '### Invoke (custom replies / DMs after mod actions)',
      'Requires **Administrator**.',
      '```',
      '{p}invoke list',
      '{p}invoke view ban',
      '{p}invoke message ban {user.mention} was banned for {reason}',
      '{p}invoke reset ban',
      '{p}invoke test ban',
      '```',
      'Targetable actions include: `ban`, `softban`, `hardban`, `unban`, `kick`, `timeout`, `untimeout`, `jail`, `unjail`, `strip`, `warn`.',
      '',
      'Templates can be channel messages or DMs depending on how you configure the invoke entry (see `{p}invoke` / help for `message` vs `dm` type on slash).',
      '',
      'Useful placeholders often include user mention/name and reason (exact set depends on action).',
    ].join('\n'),
  },
  {
    label: '11 · Welcome & leave',
    title: 'Welcome, leave messages & autorole',
    body: [
      'Requires **Manage Server**.',
      '',
      '### Channel welcomes',
      '```',
      '{p}welcome channel',
      '{p}welcome message Welcome {user.mention} to {guild.name}! You are member #{membercount}.',
      '{p}welcome enable',
      '{p}welcome disable',
      '```',
      'Run `channel` in the destination channel (or follow prompts).',
      '',
      '### DM welcomes',
      '```',
      '{p}welcome dmmessage Hey {user.name}, thanks for joining {guild.name}!',
      '{p}welcome dm',
      '{p}welcome dmtest',
      '```',
      '`dmmessage` sets the template and enables DMs. `dm` toggles. `dmtest` DMs **you** a preview.',
      '',
      '**Note:** Leave DMs are unreliable (no shared server after leave). Use leave **channel** messages instead.',
      '',
      '### Leave messages',
      '```',
      '{p}welcome leavechannel',
      '{p}welcome leavemessage **{user.name}** left **{guild.name}**.',
      '{p}welcome leave',
      '```',
      '',
      '### Autorole',
      '```',
      '{p}welcome autorole @Member',
      '```',
      'Toggles that role as an autorole on join.',
      '',
      '### View',
      '```',
      '{p}welcome view',
      '```',
      '',
      '**Template variables:** `{user}` `{user.mention}` `{user.name}` `{guild.name}` `{membercount}`',
    ].join('\n'),
  },
  {
    label: '12 · Tickets',
    title: 'Tickets (multi-type panels)',
    body: [
      'Config needs **Manage Server**. Members use the panel buttons/menus.',
      '',
      '### Basic panel',
      '```',
      '{p}ticket setup',
      '{p}ticket panel',
      '{p}ticket category',
      '{p}ticket message Need help? Open a ticket below.',
      '{p}ticket support @Support',
      '{p}ticket view',
      '```',
      '`setup` creates a default category and posts a panel. Without types, the panel has a single **Open Ticket** button.',
      '',
      '### Multi-type tickets (different categories)',
      'Discord’s `#` picker often **hides categories** — paste the **category ID** (Developer Mode → right-click category → Copy Channel ID):',
      '```',
      '{p}ticket typeadd support 123456789012345678 General Support',
      '{p}ticket typeadd appeals 234567890123456789 Ban Appeals',
      '{p}ticket typelist',
      '{p}ticket typeremove support',
      '{p}ticket panel',
      '```',
      'After adding/removing types, **re-post** `{p}ticket panel` so the dropdown updates.',
      '',
      '### Inside a ticket',
      '```',
      '{p}ticket add @user',
      '{p}ticket remove @user',
      '{p}ticket close',
      '```',
    ].join('\n'),
  },
  {
    label: '13 · Levels',
    title: 'Leveling / XP',
    body: [
      'Members earn XP from messages when enabled. Config needs **Manage Server** for setup pieces.',
      '',
      '```',
      '{p}levels setup',
      '{p}levels disable',
      '{p}levels channel',
      '{p}levels message Congrats {user.mention}, you reached level {level}!',
      '{p}levels role 5 @Active',
      '{p}levels list',
      '{p}levels stats',
      '{p}levels stats @user',
      '{p}levels leaderboard',
      '{p}lvl leaderboard',
      '```',
      '',
      '• `setup` — enable leveling',
      '• `role <level> <@role>` — reward that level (omit role to clear that level’s reward, depending on command behavior)',
      '• `stats` / `leaderboard` — member-facing XP info',
      '',
      'Aliases: `{p}lvl`, `{p}level`.',
    ].join('\n'),
  },
  {
    label: '14 · Starboard, giveaways, polls',
    title: 'Starboard, giveaways & polls',
    body: [
      '### Starboard',
      '```',
      '{p}starboard channel',
      '{p}starboard emoji ⭐',
      '{p}starboard threshold 3',
      '{p}starboard enable',
      '{p}starboard disable',
      '{p}starboard view',
      '```',
      'When a message hits the emoji threshold, it is posted to the starboard channel.',
      '',
      '### Giveaways',
      '```',
      '{p}giveaway 1h Nitro Classic',
      '{p}gw 30m 2x Discord Nitro',
      '```',
      'Duration: `s`/`m`/`h`/`d` (min ~10s). Members press **Enter**; winners are picked when it ends. Slash can set winner count.',
      '',
      '### Polls',
      '```',
      '{p}poll Should we host a movie night?',
      '```',
      'Creates a yes/no poll with voting controls.',
    ].join('\n'),
  },
  {
    label: '15 · Snipes & AFK',
    title: 'Snipes & AFK',
    body: [
      '### Snipes (Manage Messages)',
      '```',
      '{p}snipe',
      '{p}snipe 2',
      '{p}s 1',
      '{p}editsnipe',
      '{p}es 1',
      '{p}clearsnipe',
      '{p}cs',
      '```',
      '• `snipe` — recently **deleted** messages in this channel (index 1–20)',
      '• `editsnipe` — recently **edited** messages',
      '• `clearsnipe` — clear this channel’s snipe cache',
      '',
      '### AFK',
      '```',
      '{p}afk brb food',
      '{p}afk',
      '```',
      'Sets you AFK. Cleared automatically when you send a message. If someone pings an AFK member, the bot can reply with their reason.',
    ].join('\n'),
  },
  {
    label: '16 · Aliases & autoresponders',
    title: 'Aliases & autoresponders',
    body: [
      'Requires **Manage Server**.',
      '',
      '### Custom aliases',
      '```',
      '{p}alias add q ban',
      '{p}alias remove q',
      '{p}alias list',
      '```',
      'Maps a short name to an existing command. Built-in aliases already exist (see next page) — custom ones are per-server.',
      '',
      '### Autoresponders',
      '```',
      '{p}autoresponder add hi Hello there!',
      '{p}ar add rules Please read #rules',
      '{p}autoresponder remove hi',
      '{p}autoresponder list',
      '{p}autoresponder clear',
      '```',
      'By default triggers **include**-match (case-insensitive). Slash can set **exact** match.',
    ].join('\n'),
  },
  {
    label: '17 · Built-in aliases',
    title: 'Built-in command aliases',
    body: [
      'These work out of the box (same args as the real command):',
      '',
      '```',
      '{p}q          → ban',
      '{p}sban       → softban',
      '{p}hban       → hardban',
      '{p}to         → timeout',
      '{p}c          → purge',
      '{p}an / antin → antinuke',
      '{p}s          → snipe',
      '{p}es         → editsnipe',
      '{p}cs         → clearsnipe',
      '{p}lvl/level  → levels',
      '{p}h          → help',
      '{p}i / ui     → userinfo',
      '{p}si         → serverinfo',
      '{p}av         → avatar',
      '{p}gw         → giveaway',
      '{p}ar         → autoresponder',
      '{p}fp/fakeperms → fakepermissions',
      '{p}n          → nuke',
      '{p}bl/serverlock → botlock',
      '```',
      '',
      'Examples:',
      '```',
      '{p}q @user raid',
      '{p}c 100',
      '{p}s',
      '{p}an toggle on',
      '```',
    ].join('\n'),
  },
  {
    label: '18 · Admin tools',
    title: 'Admin tools: say, embed, nuke, eval',
    body: [
      '### Say / embed',
      '```',
      '{p}say Hello everyone',
      '{p}embed "Title" Description goes here',
      '```',
      'Needs **Manage Messages**. Embed color can be passed at the end depending on parser support.',
      '',
      '### Nuke (bot owners only)',
      '```',
      '{p}nuke',
      '{p}nuke #general',
      '{p}n',
      '```',
      'Deletes a channel and recreates an exact replica (perms/position/topic). Confirm flow with a short countdown — **destructive**.',
      '',
      '### Eval (bot owners only)',
      '```',
      '{p}eval 1 + 1',
      '```',
      'Runs JavaScript as the bot process. Extremely powerful — owners only.',
      '',
      '### Botlock (bot owners only)',
      'Covered in Getting Started — `{p}botlock` / `{p}bl`.',
    ].join('\n'),
  },
  {
    label: '19 · Info & fun',
    title: 'Info commands & fun',
    body: [
      '### Info',
      '```',
      '{p}help',
      '{p}help antinuke',
      '{p}ping',
      '{p}botinfo',
      '{p}serverinfo',
      '{p}si',
      '{p}userinfo @user',
      '{p}ui',
      '{p}avatar @user',
      '{p}av',
      '{p}roles',
      '{p}docs',
      '```',
      '`docs` (this guide) is restricted to the **server owner** or **bot owners**.',
      '',
      '### Fun',
      '```',
      '{p}8ball Will it rain tomorrow?',
      '{p}coinflip',
      '```',
    ].join('\n'),
  },
  {
    label: '20 · Checklist & tips',
    title: 'Owner checklist & tips',
    body: [
      '### Launch checklist',
      '1. Invite bot with needed intents/perms (members, messages, moderation)',
      '2. `{p}botlock` unlock if the bot is silent for staff',
      '3. `{p}setup`',
      '4. `{p}logging enable` + skim log channels',
      '5. `{p}antinuke toggle on` + whitelist trusted admins',
      '6. `{p}filter setup` (optional)',
      '7. `{p}antiraid toggle on` (optional)',
      '8. `{p}welcome …` + autorole',
      '9. `{p}ticket typeadd …` + `{p}ticket panel`',
      '10. `{p}fakepermissions add …` for trial mods',
      '11. Teach staff `{p}help` and a few aliases (`{p}q`, `{p}c`, `{p}to`)',
      '',
      '### Tips',
      '• Role IDs beat `#` mentions for **categories** (tickets) and fuzzy names for roles.',
      '• Hierarchy: bot’s top role must sit **above** roles it assigns; your role must be above targets.',
      '• Hardban is for people who must never return; softban is for message cleanup.',
      '• Leave **DMs** usually fail — use leave channel messages.',
      '• If commands “do nothing”, check **botlock** first.',
      '',
      '### This docs command',
      '```',
      '{p}docs',
      '```',
      'Paginate with **Prev/Next**, or jump chapters with the dropdown. Only you (server owner / bot owner) can flip these pages on the message you opened.',
      '',
      '— End of guide. Use `{p}help <command>` for a quick refresher anytime.',
    ].join('\n'),
  },
];

function applyPrefix(text: string, prefix: string): string {
  return text.replaceAll('{p}', prefix);
}

export function buildDocsEmbed(prefix: string, page: number): {
  embed: EmbedBuilder;
  page: number;
  totalPages: number;
} {
  const totalPages = DOC_PAGES.length;
  const safePage = Math.min(Math.max(0, page), totalPages - 1);
  const entry = DOC_PAGES[safePage];

  const embed = new EmbedBuilder()
    .setColor(Colors.success)
    .setTitle(`${bolt()} Blaze Docs — ${entry.title}`)
    .setDescription(applyPrefix(entry.body, prefix))
    .setFooter({
      text: `Page ${safePage + 1} of ${totalPages} • Owners / server owner only • Prefix: ${prefix}`,
    });

  return { embed, page: safePage, totalPages };
}

export function buildDocsComponents(
  page: number,
  totalPages: number,
  ownerId: string,
): ActionRowBuilder<ButtonBuilder | StringSelectMenuBuilder>[] {
  const nav = new ActionRowBuilder<ButtonBuilder>().addComponents(
    new ButtonBuilder()
      .setCustomId(`docs:page:prev:${page}:${ownerId}`)
      .setLabel('Prev')
      .setEmoji('⬅️')
      .setStyle(ButtonStyle.Secondary)
      .setDisabled(page <= 0),
    new ButtonBuilder()
      .setCustomId(`docs:page:next:${page}:${ownerId}`)
      .setLabel('Next')
      .setEmoji('➡️')
      .setStyle(ButtonStyle.Success)
      .setDisabled(page >= totalPages - 1),
  );

  const jump = new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(
    new StringSelectMenuBuilder()
      .setCustomId(`docs:jump:${ownerId}`)
      .setPlaceholder('Jump to section…')
      .addOptions(
        DOC_PAGES.map((p, i) => ({
          label: p.label.slice(0, 100),
          value: String(i),
          default: i === page,
        })),
      ),
  );

  return [nav, jump];
}
